# 网站基本信息
site_name: Vernyi_226的个人网站
site_url: https://urnaive.github.io
site_author: 晋秦
site_description: Vernyi_226的个人网站

# 页面结构
nav:
  - 关于我:
    - ME/self.md
  - 课内学习记录:
    - LEARN_withinclass/index.md
    - 线性代数:
      - LEARN_withinclass/LINEAR_ALGEBRA/1week1lesson.md
  - 课外学习记录:
    - LEARN_beyondclass/index.md
  - 二刺螈杂谈:
    - ACGN/index.md
  - 随缘记的日记:
    - DIARY/index.md

# 视觉设置
theme:
  name: material
  palette:
    primary: teal
    accent: deep_purple
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
  language: zh

# 版权声明
copyright: 晋秦 CC-BY-4.0

# LaTeX数学公式支持与取消翻页按钮（该代码块来自THU杨希杰）
extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols